version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/daniyar/postgres-data:/var/lib/mysql/data
    ports:
      - 5432:5432

#  api:
#    build: .
#    depends_on:
#      - db
#    ports:
#      - 8080:8080
