INSERT INTO USERS(ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME) VALUES (1, 'daniyar@test.com', '123', 'Daniyar', 'Testbergen');
INSERT INTO USERS(ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME) VALUES (2, 'zhake@test.com', '123', 'Zheka', 'UnitTestbergen');

INSERT INTO ROLE(ID, NAME) VALUES (1, 'USER');
INSERT INTO ROLE(ID, NAME) VALUES (2, 'ADMIN');

INSERT INTO USERS_ROLE(ID, USERS_ID, ROLE_ID) VALUES (1, 1, 1);
INSERT INTO USERS_ROLE(ID, USERS_ID, ROLE_ID) VALUES (2, 2, 2);

SELECT * FROM USERS;