DROP TABLE IF EXISTS USERS_ROLE;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLE;

CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY ,
    EMAIL VARCHAR(100),
    PASSWORD TEXT,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ROLE(
    ID SERIAL PRIMARY KEY ,
    NAME VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS USERS_ROLE(
    ID SERIAL PRIMARY KEY ,
    USERS_ID INTEGER REFERENCES USERS(ID),
    ROLE_ID INTEGER REFERENCES ROLE(ID)
);