spring:
  datasource:
    url: jdbc:h2:file:~/testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
