spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
#    schema: classpath:db/schema.sql
#    data: classpath:db/data.sql
    initialization-mode: always
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
